### ISSUE TITLE
Gemfile

### ISSUE THREAD

**Issue by rexberg** [gildasio/darcli#1]
Hi,

Love the style of the theme!

Would it be possible to get the Gemfile for the project as well? :-)

Best regards
Markus Lindberg

**Comment by gildasio** [comment]
Thank you!

So, to use this theme only the `github-pages` gem is needed, you can install it and be happy \o/

And, do you like to send a PR with this modification? This would be a great contribution!

**Comment by rexberg** [comment]
I have created a PR now, closing this issue. :-)
