### ISSUE TITLE
Certificated Error

### ISSUE THREAD

**Issue by sin9yt** [gildasio/darcli#5]
The theme always redirects to https. As a result when I set it up as a custom domain, it shows https certificate error. 

The ssl property in _config.yml does not work.

**Comment by gildasio** [comment]
Hi, @sin9yt !

When `ssl` property in `_config.yml` is true always will redirect to `https`. And when is false don't will make change in the protocol.

I tried right know the source code (the same that is online) and it's work fine.

Make sure that you have restarted your server or renegeted static pages after change `_config.yml`.
